<div id="erreurmail"></div>
<div id="erreurpassword"></div>
<div id="erreurnom"></div>
<div id="erreurprenom"></div>
<div id="erreurville"></div>
<div id="erreurtel"></div>
	<form action="" method="post" name="form1" id="form1" class="form1">
		<label for="mail">Votre adresse mail</label>
		<input type="text" id="mail" name="mail" placeholder="Ex : jean.dupont@achetervehicule.com"/>
		<label for="password">Mot de passe</label>
		<input type="password" name="password" id="password"/>
	<label for="nom">Votre nom et prénom</label>
	<input type="text" name="nom" id="nom" placeholder="Ex : Dupont"/>
	<label for="ville">Votre ville</label>
	<input type="text" name="ville" id="ville" placeholder="Ex : Paris"/>
	<input type="hidden" name="cp" id="cp"/>
	<label for="tel">Votre téléphone</label>
	<input type="text" name="tel" id="tel" placeholder="Ex : 061122334455"/>
	<input type="submit" value="S'inscrire">
	</form>
<script type="text/javascript">
function surligne(champ, erreur)
{
   if(erreur)
      champ.style.borderColor = "#df8f90";
   else
      champ.style.borderColor = "";
}
$(function(){ 
   $('form')
      .bind('submit',function(event) {
      return verifSubmit(form1);
   });
	$('#mail')
      .bind('blur',function(event) {
      verifMail();
   });
   $('#password')
      .bind('blur',function(event) {
      verifPasswordEmpty();
   });
   $('#nom')
      .bind('blur',function(event) {
      verifNomEmpty();
   });
   $('#ville')
      .bind('blur',function(event) {
      verifVilleEmpty();
   });
   $('#tel')
      .bind('blur',function(event) {
      verifTelephoneEmpty();
   });
});

function verifMail()
{
   var champ = document.getElementById("mail");
   var regMailExpression = /^[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$/;

   if(champ.value.length < 1)
   {
      surligne(champ, true);
	  document.getElementById("erreurmail").innerHTML="<div class='notif error'>Le mail est obligatoire</div>";
	  return false;
   }
   else if(!regMailExpression.test(champ.value)) {
   	  surligne(champ,true);
   	  document.getElementById("erreurmail").innerHTML="<div class='notif error'>L'adresse mail est invalide</div>";
   	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurmail").innerHTML="";
      return true;
   }
}

function verifPasswordEmpty()
{
   var password = document.getElementById("password");

   if(password.value.length < 1)
   {
     surligne(password, true);
     document.getElementById("erreurpassword").innerHTML="<div class='notif error'>Le mot de passe est obligatoire</div>";
     return false;
   }
   else
   {
      surligne(password, false);
      document.getElementById("erreurpassword").innerHTML="";
      return true;
   }
}

function verifNomEmpty()
{
   var nom = document.getElementById("nom");

   if(nom.value.length < 1)
   {
     surligne(nom, true);
     document.getElementById("erreurnom").innerHTML="<div class='notif error'>Le nom est obligatoire</div>";
     return false;
   }
   else
   {
      surligne(nom, false);
      document.getElementById("erreurnom").innerHTML="";
      return true;
   }
}

function verifVilleEmpty()
{
   var ville = document.getElementById("ville");

   if(ville.value.length < 1)
   {
     surligne(ville, true);
     document.getElementById("erreurville").innerHTML="<div class='notif error'>La ville est obligatoire</div>";
     return false;
   }
   else
   {
      surligne(ville, false);
      document.getElementById("erreurville").innerHTML="";
      return true;
   }
}

function verifTelephoneEmpty()
{
   var tel = document.getElementById("tel");
   var regMailExpression = /^[0-9]+$/;

   if(tel.value.length < 1)
   {
     surligne(tel, true);
     document.getElementById("erreurtel").innerHTML="<div class='notif error'>Le téléphone est obligatoire</div>";
     return false;
   }
   else if(!regMailExpression.test(tel.value)) {
      surligne(tel,true);
      document.getElementById("erreurtel").innerHTML="<div class='notif error'>Le téléphone est invalide</div>";
      return false;
   }
   else
   {
      surligne(tel, false);
      document.getElementById("erreurtel").innerHTML="";
      return true;
   }
}

function verifSubmit(f) 
{
   var mailOk = verifMail();
   var mdpOk = verifPasswordEmpty();
   var nomOk = verifNomEmpty();
   var villeOk = verifVilleEmpty();
   var telOk = verifTelephoneEmpty();
   
   if(mailOk && mdpOk && nomOk && villeOk && telOk)
      return true;
   else
   {
      alert("Veuillez remplir correctement tous les champs");
      return false;
   }
}
</script>