<div id="erreurmail3"></div>
<div id="erreurpassword3"></div>
<div id="erreurnom3"></div>
<div id="erreurville3"></div>
<div id="erreurtel3"></div>
	<form action="" method="post" name="form3" id="form3" class="form3">
		<label for="mail_inscript">Votre adresse mail</label>
		<input type="text" id="mail_inscript3" name="mail_inscript3" placeholder="Ex : jean.dupont@achetervehicule.com"/>
		<label for="password_inscript">Mot de passe</label>
		<input type="password" name="password_inscript3" id="password_inscript3"/>
	<label for="nom_inscript">Votre nom et prénom</label>
	<input type="text" name="nom3" id="nom3" placeholder="Ex : Dupont"/>
	<label for="ville">Votre ville</label>
	<input type="text" name="ville3" id="ville3" placeholder="Ex : Paris"/>
	<input type="hidden" name="cp3" id="cp3"/>
	<label for="tel">Votre téléphone</label>
	<input type="text" name="tel3" id="tel3" placeholder="Ex : 061122334455"/>
	<input id="inscription3" name="inscription3" type="submit" value="S'inscrire">
	</form>
<script type="text/javascript">
function surligne(champ, erreur)
{
   if(erreur)
      champ.style.borderColor = "#df8f90";
   else
      champ.style.borderColor = "";
}
$(function(){ 
   $('#form3')
      .bind('submit',function(event) {
      return verifSubmit3(form3);
   });
    $('#mail_inscript3')
      .bind('blur',function(event) {
      verifMail3();
     });
  $('#password_inscript3')
      .bind('blur',function(event) {
      verifPassword3();
     });
    $('#nom3')
      .bind('blur',function(event) {
      verifNom3();
     });
    $('#ville3')
      .bind('blur',function(event) {
      verifVille3();
     });
    $('#tel3')
      .bind('blur',function(event) {
      verifTel3();
     });
});

function verifMail3()
{
   var champ = document.getElementById("mail_inscript3");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurmail3").innerHTML="<div class='notif error'>Le mail est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurmail3").innerHTML="";
      return true;
   }
}

function verifPassword3()
{
   var champ = document.getElementById("password_inscript3");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurpassword3").innerHTML="<div class='notif error'>Le password est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurpassword3").innerHTML="";
      return true;
   }
}

function verifNom3()
{
   var champ = document.getElementById("nom3");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurnom3").innerHTML="<div class='notif error'>Le nom est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurnom3").innerHTML="";
      return true;
   }
}

function verifVille3()
{
   var champ = document.getElementById("ville3");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurville3").innerHTML="<div class='notif error'>La ville est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurville3").innerHTML="";
      return true;
   }
}
function verifTel3()
{
   var champ = document.getElementById("tel3");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurtel3").innerHTML="<div class='notif error'>Le téléphone est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurtel3").innerHTML="";
      return true;
   }
}




function verifSubmit3(f) 
{
   var mailOk3 = verifMail3();
   var passwordOk3 = verifPassword3();
   var nomOk3 = verifNom3();
   var villeOk3 = verifVille3();
   var telOk3 = verifTel3();
   
   if(mailOk3 && passwordOk3 && nomOk3 && villeOk3 && telOk3){
      return true;
    }
   else
   {
      alert("Veuillez remplir correctement tous les champs");
      return false;
   }
}
</script>