<?php foreach ($compte as $unCompte) {?>
<h1>Mon compte</h1>
<?php if ($_GET['deleted'] == 1) {
	echo "<div class='notif success'>Votre annonce a bien été supprimée</div>";
}
if ($_GET['deleted'] == 0) {
	echo "<div class='notif error'>Une erreur est survenue lors de la suppression du compte</div>";
} ?>
<br />
<div id="compte_left">
<h2>Mes informations</h2>
<form action="" method="post" name="form3" id="form3" class="form3">
	<label for="mail">Votre adresse mail</label>
	<input type="text" id="mail" name="mail" value="<?= $unCompte->getAttribute("mail"); ?>"/>
	<label for="nom">Votre nom et prénom</label>
	<input type="text" name="nom" id="nom" value="<?= $unCompte->getAttribute("nom"); ?>"/>
	<label for="cp">Votre code postal</label>
	<input type="text" name="cp" id="cp" value="<?= $unCompte->getAttribute("code_postal"); ?>"/>
	<label for="tel">Votre téléphone</label>
	<input type="text" name="tel" id="tel" value="<?= $unCompte->getAttribute("telephone"); ?>"/>
	<input type="hidden" id="id_membre" name="id_membre"/>
	<input type="submit" value="valider">
	</form>
</div>
<div id="compte_left_2">
<h2>Mes informations</h2>
<form action="" method="post" name="form3" id="form3" class="form3">
	<p>Votre adresse mail :<?= $unCompte->getAttribute("mail"); ?> </p>
	<p>Votre nom et prénom :<?= $unCompte->getAttribute("nom"); ?> </p>
	<p>Votre code postal :<?= $unCompte->getAttribute("code_postal"); ?> </p>
	<p>Votre téléphone :<?= $unCompte->getAttribute("telephone"); ?> </p>
	<a hre="#" id="edit_btn">Modifier</a>
	</form>
</div>
<?php } ?>
<div id="compte_right">
<h2>Mes annonces</h2>


<table>
	<thead>
		<td>Titre<td>
		<td>Action</td>
	</thead>
	<?php foreach ($liste as $uneliste) { ?>
	<tbody>
		<td><?= $uneliste->getAttribute("titre"); ?><td>
		<td><a href="/?controller=user&action=compte&delete=1&id=<?= $uneliste->getAttribute("id"); ?>">Supprimer</a></td>
	</tbody>
<?php } ?>
</table>
 

</div>
<script type="text/javascript">
$('#compte_left').hide();

$('#edit_btn').click(function() {
	$('#compte_left_2').hide();
	$('#compte_left').show();
});
</script>