<?php foreach ($compte as $unCompte) {?>
<div id="erreurmailp"></div>
<div id="erreurnomprenomp"></div>
<div id="erreurcpp"></div>
<div id="erreurtelp"></div>
<h1>Mon compte</h1>
<?php if ($_GET['deleted'] == 1) {
	echo "<div class='notif success'>Votre annonce a bien été supprimée</div>";
}
if ($_GET['deleted'] == 2) {
	echo "<div class='notif error'>Une erreur est survenue lors de la suppression du compte</div>";
} ?>
<br />
<div id="compte_left">
<h2>Mes informations</h2>
<form action="" method="post" name="form3" id="form3" class="form3">
	<label for="mail">Votre adresse mail</label>
	<input type="text" id="mail" name="mail" value="<?= $unCompte->getAttribute("mail"); ?>"/>
	<label for="nom">Votre nom et prénom</label>
	<input type="text" name="nom" id="nom" value="<?= $unCompte->getAttribute("nom"); ?>"/>
	<label for="cp">Votre code postal</label>
	<input type="text" name="cp" id="cp" value="<?= $unCompte->getAttribute("code_postal"); ?>"/>
	<label for="tel">Votre téléphone</label>
	<input type="text" name="tel" id="tel" value="<?= $unCompte->getAttribute("telephone"); ?>"/>
	<input type="hidden" id="id_membre" name="id_membre"/>
	<input type="submit" value="valider">
	</form>
</div>
<div id="compte_left_2">
<h2>Mes informations</h2>
<form action="" method="post" name="form3" id="form3" class="form3">
	<p id="mailp">Votre adresse mail : <br /><?= $unCompte->getAttribute("mail"); ?> </p>
	<p id="nomprenomp">Votre nom et prénom : <br /><?= $unCompte->getAttribute("nom"); ?> </p>
	<p id="cpp">Votre code postal : <br /><?= $unCompte->getAttribute("code_postal"); ?> </p>
	<p id="telp">Votre téléphone : <br />0<?= $unCompte->getAttribute("telephone"); ?> </p>
	<a hre="#" id="edit_btn">Modifier</a>
	</form>
</div>
<?php } ?>
<div id="compte_right">
<h2>Mes annonces</h2>


<table id="list_annonce">
	<thead>
		<td>Titre de l'annonce<td>
		<td>Action</td>
	</thead>
	<?php foreach ($liste as $uneliste) { ?>
	<tbody>
		<td><?= $uneliste->getAttribute("titre"); ?><td>
		<td><a class="delete" href="/?controller=user&action=compte&delete=1&id=<?= $uneliste->getAttribute("id"); ?>"><img src="<?= PUBLIC_ROOT ?>img/trash.gif" /></a></td>
	</tbody>
<?php } ?>
</table>
 

</div>
<script type="text/javascript">
$('#compte_left').hide();

$('#edit_btn').click(function() {
	$('#compte_left_2').hide();
	$('#compte_left').show();
});

function surligne(champ, erreur)
{
   if(erreur)
      champ.style.borderColor = "#df8f90";
   else
      champ.style.borderColor = "";
}
$(function(){ 
   $('#form3')
      .bind('submit',function(event) {
      return verifSubmitco(form3);
   });
    $('#mailp')
      .bind('blur',function(event) {
      verifPMail();
     });
    $('#nomprenomp')
      .bind('blur',function(event) {
      verifPnomprenom();
     });
    $('#cpp')
      .bind('blur',function(event) {
      verifPCp();
     });
     $('#telp')
      .bind('blur',function(event) {
      verifPTel();
     });
});


function verifPMail()
{
   var champ = document.getElementById("mailp");
   var regMailExpression = /^[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$/;

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurmailp").innerHTML="<div class='notif error'>Le mail est obligatoire</div>";
	  return false;
   }
   else if(!regMailExpression.test(champ.value)) {
   	  surligne(champ,true);
   	  document.getElementById("erreurmailp").innerHTML="<div class='notif error'>L'adresse mail est invalide</div>";
   	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurmailp").innerHTML="";
      return true;
   }
}

function verifPnomprenom()
{
   var champ = document.getElementById("nomprenomp");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurnomprenomp").innerHTML="<div class='notif error'>Le nom est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurnomprenomp").innerHTML="";
      return true;
   }
}


function verifPCp()
{
   var champ = document.getElementById("cpp");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurcpp").innerHTML="<div class='notif error'>Le code postal est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurcpp").innerHTML="";
      return true;
   }
}

function verifPTel()
{
   var champ = document.getElementById("telp");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurtelp").innerHTML="<div class='notif error'>Le message est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurtelp").innerHTML="";
      return true;
   }
}




function verifSubmitco(f) 
{
   var mailpOK = verifPMail();
   var nomprenompOK = verifPnomprenom();
   var cppOk = verifPCp();
   var telpOk = verifPTel();
   
   if(mailpOK && nomprenompOK && cppOk && telpOk) {
      return true;
    }
   else
   {
      alert("Veuillez remplir correctement tous les champs");
      return false;
   }
}
</script>