<div id="erreurmail"></div>
<div id="erreurpassword"></div>
<div id="notif_connect">
</div>
<form action="#" method="post" name="connexionForm" id="connexionForm">
	<label for="mail_connect">Votre adresse mail</label>
	<input type="text" id="mail_connect" name="mail_connect" placeholder="Ex : jean.dupont@achetervehicule.com"/>
	<label for="password_connect">Mot de passe</label>
	<input type="password" name="password_connect" id="password_connect"/>
<input type="submit" id="connexion" value="Connexion">
</form>

<script type="text/javascript">
function surligne(champ, erreur)
{
   if(erreur)
      champ.style.borderColor = "#df8f90";
   else
      champ.style.borderColor = "";
}
$(function(){ 
   $('#connexionForm')
      .bind('submit',function(event) {
      return verifSubmitC(connexionForm);
   });
   $('#mail_connect')
      .bind('blur',function(event) {
      verifMailC();
   });
   $('#password_connect')
      .bind('blur',function(event) {
      verifPasswordEmptyC();
   });
});


function verifMailC()
{
   var champ = document.getElementById("mail_connect");
   var regMailExpression = /^[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$/;

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurmail").innerHTML="<div class='notif error'>Le mail est obligatoire</div>";
	  return false;
   }
   else if(!regMailExpression.test(champ.value)) {
   	  surligne(champ,true);
   	  document.getElementById("erreurmail").innerHTML="<div class='notif error'>L'adresse mail est invalide</div>";
   	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurmail").innerHTML="";
      return true;
   }
}

function verifPasswordEmptyC()
{
   var password = document.getElementById("password_connect");

   if(password.value.length < 1)
   {
     surligne(password, true);
     document.getElementById("erreurpassword").innerHTML="<div class='notif error'>Le mot de passe est obligatoire</div>";
     return false;
   }
   else
   {
      surligne(password, false);
      document.getElementById("erreurpassword").innerHTML="";
      return true;
   }
}

function verifSubmitC(f) 
{
   var mailOkC = verifMailC();
   var mdpOkC = verifPasswordEmptyC();
   var success = 0;
   if(mailOkC && mdpOkC) {
   	success = 1;
   }
   else
   {
      alert("Veuillez remplir correctement tous les champs");
      return false;
   }
   if (success == 1) {					 
			$.ajax({
			   type: "POST",
			   url: "http://localhost/projetB3/users/connect",
			   data: "mail_connect="+$("#mail_connect").val()+"&password_connect="+$("#password_connect").val(),
			   success: function(msg){
					if(msg==0)
					{
                  $("#notif_connect").html("<div class='notif error'>Login ou mot de passe incorrect</div>");
						
						
					}
               else if(msg==2) {
                  $("#notif_connect").html("<div class='notif error'>Compte en attente de validation</div>");
               }
               else if(msg==3) {
                  $("#notif_connect").html("<div class='notif error'>Compte banni.</div>");
               }
					else
					{
						$("#notif_connect").html("<div class='notif success'>Connexion Réussie ! Redirection en cours...</div>");
                  redirectOk();
					}
			   }
			});
			return false;
	}
}

function redirectOk() {
   window.location.href('http://localhost/ClientWebVehicule/');
   setTimeout("redirectOk()",1000);
}
</script>