<div id="gauche">
	<h1>Les dernières annonces postées</h1>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.50/images/477/477324765164.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2><a href="fiche.php">Bmw x1 luxe sdrive 2.0d 177 ch</a></h2>
			<p>BMW X1 luxe sdrive 2.0d 177ch
				marron métalisé, intérieur cuir noir
				GPS 16/9 ème avec disque dur et kit connexion USB
				volant multi-fonctions avec téléphone bluetooth
				phares bi-xénon diréctionnels adaptatifs+ feux arrières leds
				aide au stationnement
				rétroviseurs électrochromes électriques rabatables
				clim auto bi-zones, régulateur de vitesse et de distance
				véhicule garanti+ assistance BMW pack mobilité+ jusqu'au 14/02/2014 
			</p>
			<div class="detail-annonce">
				<p>Paris (75) - 2010 - Diesel - 46000Km</p>
				<div class="liste-prix">
					Prix : <span>25000 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.60/images/375/375326832544.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2>RENAULT CLIO 3 1.5 DCI 85CH PRIVILEGE ( 1ere MAIN)</h2>
			<p>Version : CLIO III 1.5 DCI 85
				Année : 2008
				Kilométrage : 123066 km
				Nombre de portes : 5 portes
				Puissance fiscale : 5 CV
				Boîte de vitesse : mécanique
				Énergie : Diesel
				Mise en circulation : 25/06/2008
				Couleur extérieure : NOIRE
				couleur interieur: marron claire
				Première main : oui

				Options & équipements
				Carrosserie / Extérieur
				- Peinture integrale
				- 4 Vitres electriques

				Options intérieures
				- Volant cuir reglable

				Sécurité / Antivol
				- ABS
				- Airbags frontaux
				- Anti demarrage
			</p>
			<div class="detail-annonce">
				<p>Thiais (94) - 2008 - Diesel - 123066Km</p>
				<div class="liste-prix">
					Prix : <span>6290 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.50/images/229/229323303436.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2>Ford focus rs mk2 305CV</h2>
			<p>FORD FOCUS RS 305 CV 29/10/2009 Bleue Métallisé 1ère Main
				Ford Focus RS 2.5T 305CH 3p Berline

				* Marque : Ford
				* Modèle : Focus RS
				* Mise en circulation: 29 Octobre 2009
				* Énergie : Essence
				* kilométrage: 34 500 KMS
				* Boite : BVM 6
				* Puissance fiscale : 21 cv
				* couleur: blanc glacier
				* puissance din : 305 ch
				* nombres de portes : 3
				Options du vehicule :

				Pack RS :
				- Sièges avant et banquette Recaro cuir/Alcantara
				- Aide de stationnement arrière
				- Démarrage sans clef keyless go
			</p>
			<div class="detail-annonce">
				<p>Franconville (95) - 2009 - Essence - 34500Km</p>
				<div class="liste-prix">
					Prix : <span>26700 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.50/images/477/477326977994.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2>Seat leon</h2>
			<p>bonjour je vend une seat leon 2 140 fap sport blanche boite 6 vitesse acheter neuve le 18/01/2011.
				elle comptabilise 31000 km la révision viens d'être faite les pneu avant changer il y a 5000 km.
				c'est une première main

				extérieur:

				vitres électriques, rétroviseur électrique et dégivrant
				rétroviseur rabatable électriquement
				jantes alu, feux LED, radar de recule, détecteur de pluie, allumage auto des feux
			</p>
			<div class="detail-annonce">
				<p>Buchelay (78) - 2011 - Diesel - 31000Km</p>
				<div class="liste-prix">
					Prix : <span>17000 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.60/images/479/479328092378.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2>MERCEDES - CLASSE C 220 CDI - Avangarde</h2>
			<p>- Non Fumeur
				- Boite de vitesse Automatique 5 rapports
				- 10 CV fiscaux (170 CV)
				- Sièges Cuir/Tissu Artico
				- Phares Xénon
				- GPS Grand écran (Command car)
				- Bluetooth Téléphonie confort
				- Aide au stationnement (avant et arrière)
				- Eclairage automatique
				- Feu de virages
				- Essuie-glace capteur de pluie
				- Régulateur de vitesse Tempomat – Speedtronic
				- Rétroviseurs anti-éblouissants
				- Rétroviseurs extérieurs rabattables électriquement
				- Climatisation bi-zone automatique
			</p>
			<div class="detail-annonce">
				<p>Suresnes (92) - 2007 - Diesel - 63000Km</p>
				<div class="liste-prix">
					Prix : <span>17500 €</span>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="droite">
	<h1>Les plus vus</h1>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.60/images/479/479328092378.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h3>MERCEDES - CLASSE C 220 CDI - Avangarde</h3>
			<div class="detail-annonce">
				<div class="liste-prix">
					Prix : <span>17500 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.50/images/477/477326977994.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h3>Seat leon</h3>
			<div class="detail-annonce">
				<div class="liste-prix">
					Prix : <span>17000 €</span>
				</div>
			</div>
		</div>
	</div>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.60/images/375/375326832544.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h3>RENAULT CLIO 3 1.5 DCI 85CH PRIVILEGE ( 1ere MAIN)</h3>
			<div class="detail-annonce">
				<div class="liste-prix">
					Prix : <span>6290 €</span>
				</div>
			</div>
		</div>
	</div>
	<h1>Une question ?</h1>
	<div id="support">
		<h2>Nos conseillers sont à votre disposition :</h2>
		<div id="tel-support">01 43 43 50 30</div>
		de 9h à 18h
	</div>
</div>