<h1>Formulaire de contact</h1>
<p>
	Si vous avez des questions, des suggestions ou tout autre problème, n'hésitez pas a utiliser notre formulaire de contact ci-dessous.
</p>
<div id="contact_form">
	<form action="">
		<label for="nom">Votre nom</label>
		<input type="text" name="nom" id="nom" placeholder="Ex : Dupont"/>
		<label for="prenom">Votre prénom</label>
		<input type="text" name="prenom" id="prenom" placeholder="Ex : Jean"/>
		<label for="mail">Votre adresse mail</label>
		<input type="text" id="mail" name="mail" placeholder="Ex : jean.dupont@achetervehicule.com"/>
		<label for="sujet">Sujet du message</label>
		<input type="text" name="sujet" id="sujet" placeholder="Ex : problème d'affichage"/>
		<label for="message">Votre message</label>
		<textarea name="message" id="message" placeholder="Votre message"></textarea>
		<input type="submit" value="Contactez-nous !">
	</form>
</div>
<div id="plan_contact">
	<iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?f=q&amp;source=s_q&amp;hl=fr&amp;geocode=&amp;q=53+rue+de+grenelle&amp;aq=&amp;sll=48.680793,2.502588&amp;sspn=1.860573,4.938354&amp;ie=UTF8&amp;hq=&amp;hnear=53+Rue+de+Grenelle,+75007+Paris,+%C3%8Ele-de-France&amp;ll=48.854654,2.325339&amp;spn=0.007243,0.01929&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed&amp;iwloc=near"></iframe>
</div>