<h1>Déposer votre annonce</h1>
<div id="erreurtitre"></div>
<div id="erreurdescription"></div>
<div id="erreurprix"></div>
<div id="erreurannee"></div>
<div id="erreurkm"></div>
<div id="erreurenergie"></div>
<form action="" method="post" id="form2">
	<div id="mid_left">
		<label>Votre titre :</label>
		<input type="text" name="titre" placeholder="Ex: Peugeot 206 noir"id="titre">
		<label>Votre description :</label>
		<textarea name="description" id="description"></textarea>
		<label>Votre catégorie :</label>
		<select name="categorie" id="categorie">
			<option value="1" id="voiture">voiture</option>
			<option value="2" id="moto">moto</option>
			<option value="3" id="scooter">scooter</option>
		</select>
		<label>Votre photo:</label>
		<input type="file" multiple name="photo" value="" id="photo">
	</div>
	<div id="mid_right">
		<label>Votre prix :</label>
		<input type="text" name="prix" placeholder="Ex: 2000" id="prix">
    <label>Kilomètres:</label>
    <input type="text" name="km" placeholder="Ex: 210 000" id="km">
		<label>Votre  année:</label>
		<input type="text" name="annee" placeholder="Ex: 2012" id="annee">
		<label>Votre energie :</label>
    <select name="energie" id="energie">
      <option value="essence">Essence</option>
      <option value="diesel">Diesel</option>
      <option value="gpl">GPL</option>
      <option value="electrique">Electrique</option>
    </select>
    <div id="show_voiture">
		<label>Boite de vitesse :</label>
    <select name="boite_vitesse" id="boite_vitesse">
      <option value="automatique">Automatique</option>
      <option value="manuelle">Manuelle</option>
    </select>
		<label>Nombre deplaces :</label>
		<input type="text" name="nb_places" placeholder="Ex: 5" id="nb_places">
		</div>
		<div id="show_cylindree" style="display:none;">
		<label>Votre cylindrée:</label>
		<input type="text" name="cylindree" placeholder="Ex: 125" id="cylindree">
		</div>
		<input type="submit" value="Valider" id="envoyer">
	</div>
</form>
	
<script type="text/javascript">
 	$("#voiture").click(function () {
 		$("#show_cylindree").hide();
 		$("#show_voiture").show();
	});
	$("#moto").click(function () {
 		$("#show_cylindree").show();
 		$("#show_voiture").hide();
	});
	$("#scooter").click(function () {
 		$("#show_cylindree").show();
 		$("#show_voiture").hide();
	});

</script>

<script type="text/javascript">
function surligne(champ, erreur)
{
   if(erreur)
      champ.style.borderColor = "#df8f90";
   else
      champ.style.borderColor = "";
}
$(function(){ 
   $('#form2')
      .bind('submit',function(event) {
      return verifSubmit2(form2);
   });
    $('#titre')
      .bind('blur',function(event) {
      verifTitre();
     });
	$('#description')
      .bind('blur',function(event) {
      verifDescription();
     });
    $('#prix')
      .bind('blur',function(event) {
      verifPrix();
     });
    $('#annee')
      .bind('blur',function(event) {
      verifAnnee();
     });
    $('#km')
      .bind('blur',function(event) {
      verifAnnee();
     });
     $('#energie')
      .bind('blur',function(event) {
      verifEnergie();
     });
});

function verifTitre()
{
   var champ = document.getElementById("titre");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurtitre").innerHTML="<div class='notif error'>Le titre est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurtitre").innerHTML="";
      return true;
   }
}

function verifDescription()
{
   var champ = document.getElementById("description");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurdescription").innerHTML="<div class='notif error'>La description est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurdescription").innerHTML="";
      return true;
   }
}

function verifPrix()
{
   var champ = document.getElementById("prix");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurprix").innerHTML="<div class='notif error'>Le prix est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurprix").innerHTML="";
      return true;
   }
}

function verifAnnee()
{
   var champ = document.getElementById("annee");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurannee").innerHTML="<div class='notif error'>L'année est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurannee").innerHTML="";
      return true;
   }
}
function verifKm()
{
   var champ = document.getElementById("km");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
    document.getElementById("erreurkm").innerHTML="<div class='notif error'>Le kilométrage est obligatoire</div>";
    return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurkm").innerHTML="";
      return true;
   }
}
function verifEnergie()
{
   var champ = document.getElementById("energie");

   if(champ.value.length < 1)
   {
    surligne(champ, true);
	  document.getElementById("erreurenergie").innerHTML="<div class='notif error'>L'énergie est obligatoire</div>";
	  return false;
   }
   else
   {
      surligne(champ, false);
      document.getElementById("erreurenergie").innerHTML="";
      return true;
   }
}



function verifSubmit2(f) 
{
   var titreOk = verifTitre();
   var descriptionOk = verifDescription();
   var prixOk = verifPrix();
   var anneeOk = verifAnnee();
   var kmOk = verifKm();
   var energieOk = verifEnergie();
   
   if(titreOk && descriptionOk && prixOk && anneeOk && kmOk && energieOk){
      return true;
    }
   else
   {
      alert("Veuillez remplir correctement tous les champs");
      return false;
   }
}
</script>