<xsl:when type_vehicule="moto">
	<div id="gauche">
		<h1>Les dernières annonces postées</h1>
		<?php foreach($vehicules as $vehicule) { ?>
		<div class="annonce">
			<div class="photo-annonce">
				<img src="http://193.164.197.50/images/861/861212110447273.jpg" alt="">
			</div>
			<div class="description-annonce">
				<h2><a href="fiche.php"><?= $vehicule->getAttribute("titre"); ?></a></h2>
				<p><?= $vehicule->getAttribute("description"); ?></p>
				<div class="detail-annonce">
					<p>Paris (75) - <?= $vehicule->getAttribute("annee"); ?> - <?= $vehicule->getAttribute("energie"); ?> - <?= $vehicule->getAttribute("km"); ?>Km</p>
					<div class="liste-prix">
						Prix : <span><?= $vehicule->getAttribute("prix"); ?> €</span>
					</div>
				</div>
			</div>
		</div>
		<?php } ?>
	</div>
</xls>
<div id="droite">
	<h1>Les plus vus</h1>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.50/images/861/861212110447273.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h3>MERCEDES - CLASSE C 220 CDI - Avangarde</h3>
			<div class="detail-annonce">
				<div class="liste-prix">
					Prix : <span>17500 €</span>
				</div>
			</div>
		</div>
	</div>
	<h1>Une question ?</h1>
	<div id="support">
		<h2>Nos conseillers sont à votre disposition :</h2>
		<div id="tel-support">01 43 43 50 30</div>
		de 9h à 18h
	</div>
</div>