<div id="gauche">
	<h1>Les derniers scooters postées</h1>
	<?php foreach($vehicules as $vehicule) {
	?>
	<div class="annonce">
		<div class="photo-annonce">
			<img src="http://193.164.197.60/images/471/471311012087222.jpg" alt="">
		</div>
		<div class="description-annonce">
			<h2><a href="<?= SITE_ROOT; ?>vehicule/<?= $vehicule->getAttribute("id")."-".strtolower(str_replace(" ", "-", $vehicule->getAttribute("titre"))); ?>"><?= $vehicule->getAttribute("titre"); ?></a></h2>
			<p><?= $vehicule->getAttribute("description"); ?></p>
			<div class="detail-annonce">
				<p><?= $vehicule->firstChild->getAttribute("ville"); ?> (<?= substr($vehicule->firstChild->getAttribute("code_postal"),0,2); ?>) - <?= $vehicule->getAttribute("annee"); ?> - <?= $vehicule->getAttribute("energie"); ?> - <?= $vehicule->getAttribute("km"); ?>Km</p>
				<div class="liste-prix">
					Prix : <span><?= $vehicule->getAttribute("prix"); ?> €</span>
				</div>
			</div>
		</div>
	</div>
	<?php } ?>
</div>
<div id="droite">
	<h1>publicité</h1>
	<div class="annonce">
		<img src="<?= PUBLIC_ROOT ?>img/scooter.png" />
	<h1>publicité</h1>
		<img src="<?= PUBLIC_ROOT ?>img/bmwaudi.jpg" />
	
	</div>
	<h1>Une question ?</h1>
	<div id="support">
		<h2>Nos conseillers sont à votre disposition :</h2>
		<div id="tel-support">01 43 43 50 30</div>
		de 9h à 18h
	</div>
</div>